#!/usr/bin/env python3
"""
Daily/Weekly/Monthly Report Generator.
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from engine import NOWScorer, AssetRegistry, SimulatedDataProvider
from engine.ranking import Ranker
from database import SQLiteStore


def generate_report(period: str = "daily"):
    """Generate a report for the given period."""
    store = SQLiteStore("data/now_index.db")
    scores = store.get_latest_snapshot()
    if not scores:
        print("No data available for report")
        return

    now = datetime.now(timezone.utc)
    report_dir = Path(f"docs/reports/{period}")
    report_dir.mkdir(parents=True, exist_ok=True)

    # Sort by score descending
    sorted_scores = sorted(scores, key=lambda s: s.get("score", 0), reverse=True)

    lines = [
        f"# NOW Index {period.capitalize()} Report",
        f"",
        f"**Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Total Assets:** {len(sorted_scores)}",
        f"",
        f"## Top 10",
        f"",
        f"| Rank | Ticker | Name | Score | Asset Class |",
        f"|------|--------|------|-------|-------------|",
    ]

    for i, s in enumerate(sorted_scores[:10], 1):
        lines.append(
            f"| {i} | {s.get('ticker', 'N/A')} | {s.get('name', 'N/A')} | "
            f"{s.get('score', 0):.1f} | {s.get('asset_class', 'N/A')} |"
        )

    lines.extend([
        f"",
        f"## Summary Statistics",
        f"",
        f"- **Average Score:** {sum(s.get('score', 0) for s in sorted_scores) / len(sorted_scores):.1f}",
        f"- **Top Score:** {sorted_scores[0].get('score', 0):.1f} ({sorted_scores[0].get('ticker', 'N/A')})",
        f"- **Bottom Score:** {sorted_scores[-1].get('score', 0):.1f} ({sorted_scores[-1].get('ticker', 'N/A')})",
        f"- **Asset Classes:** {len(set(s.get('asset_class', '') for s in sorted_scores))}",
        f"",
        f"---",
        f"*Generated by NOW Index automated reporting system*",
    ])

    filename = f"{now.strftime('%Y-%m-%d')}_{period}.md"
    filepath = report_dir / filename
    filepath.write_text("\n".join(lines) + "\n")
    print(f"Report saved: {filepath}")


def main():
    periods = ["daily", "weekly", "monthly"]
    for period in periods:
        generate_report(period)
    return 0


if __name__ == "__main__":
    sys.exit(main())
